"""Generate a structured PDF report for an investigation."""
import time
from fpdf import FPDF
from . import graph_store as gs


# Threat assessment color map (R, G, B)
_TA_COLORS = {
    "benign": (86, 211, 100),        # green
    "suspicious": (227, 179, 65),    # yellow
    "likely_malicious": (248, 81, 73),  # orange-red
    "malicious": (200, 30, 30),      # red
}


class _BouncePDF(FPDF):
    """Custom PDF with header/footer."""

    _FONT_DIR = "/usr/share/fonts/truetype/dejavu"

    def __init__(self, inv_id: str, seed_value: str):
        super().__init__()
        self._inv_id = inv_id
        self._seed_value = seed_value
        # Register DejaVu Sans (Unicode-capable TTF fonts)
        self.add_font("DejaVu", "", f"{self._FONT_DIR}/DejaVuSans.ttf")
        self.add_font("DejaVu", "B", f"{self._FONT_DIR}/DejaVuSans-Bold.ttf")
        self.add_font("DejaVuMono", "", f"{self._FONT_DIR}/DejaVuSansMono.ttf")
        self.add_font("DejaVuMono", "B", f"{self._FONT_DIR}/DejaVuSansMono-Bold.ttf")

    def header(self):
        self.set_font("DejaVu", "B", 14)
        self.cell(0, 8, "BOUNCE-CTI Investigation Report", new_x="LMARGIN", new_y="NEXT")
        self.set_font("DejaVu", "", 9)
        self.set_text_color(130, 130, 130)
        self.cell(0, 5, f"Investigation: {self._inv_id}  |  Primary seed: {self._seed_value}",
                  new_x="LMARGIN", new_y="NEXT")
        self.set_text_color(0, 0, 0)
        self.line(10, self.get_y() + 2, 200, self.get_y() + 2)
        self.ln(6)

    def footer(self):
        self.set_y(-15)
        self.set_font("DejaVu", "", 8)
        self.set_text_color(130, 130, 130)
        self.cell(0, 10, f"Page {self.page_no()}/{{nb}}  |  Generated by Bounce-CTI",
                  align="C")


def _safe(val) -> str:
    """Coerce any value to a safe string for PDF output."""
    if val is None:
        return ""
    if isinstance(val, str):
        return val
    if isinstance(val, dict) and "value" in val:
        return str(val["value"])
    return str(val)


_BULLET = chr(8226)  # •

# Effective text width for A4 portrait (210mm - 10mm left - 10mm right)
_EW = 190


def _bullet_cell(pdf: _BouncePDF, text: str, multi=False):
    """Render a bulleted line. Uses multi_cell for wrapping if multi=True."""
    bulleted = f"{_BULLET}  {text}"
    pdf.x = pdf.l_margin  # reset x before each output
    if multi:
        pdf.multi_cell(_EW, 4.5, bulleted)
    else:
        pdf.cell(0, 4.5, bulleted, new_x="LMARGIN", new_y="NEXT")


def _section_title(pdf: _BouncePDF, title: str):
    pdf.set_font("DejaVu", "B", 11)
    pdf.set_fill_color(30, 30, 40)
    pdf.set_text_color(255, 255, 255)
    pdf.cell(0, 7, f"  {title}", fill=True, new_x="LMARGIN", new_y="NEXT")
    pdf.set_text_color(0, 0, 0)
    pdf.ln(3)


def _threat_badge(pdf: _BouncePDF, assessment: str):
    ta = (assessment or "unknown").lower().replace(" ", "_")
    r, g, b = _TA_COLORS.get(ta, (139, 148, 158))
    pdf.set_font("DejaVu", "B", 12)
    pdf.set_text_color(r, g, b)
    pdf.cell(0, 8, f"Threat Assessment: {ta.upper()}", new_x="LMARGIN", new_y="NEXT")
    pdf.set_text_color(0, 0, 0)
    pdf.ln(2)


def generate_pdf(inv_id: str) -> bytes:
    """Generate a PDF report for the given investigation. Returns PDF bytes."""
    graph = gs.get_graph(inv_id)
    nodes = graph.get("nodes", [])
    edges = graph.get("edges", [])

    # Find the report node
    report_node = None
    for n in nodes:
        if n.get("type") == "report" and n.get("value") == "investigation_summary":
            report_node = n
            break

    report = report_node.get("metadata", {}) if report_node else {}

    # Get investigation metadata
    with gs.conn() as c:
        inv_row = c.execute("SELECT * FROM investigations WHERE id=?", (inv_id,)).fetchone()
    inv = dict(inv_row) if inv_row else {}

    seed_value = inv.get("seed_value", inv_id)
    seed_type = inv.get("seed_type", "unknown")

    pdf = _BouncePDF(inv_id, seed_value)
    pdf.alias_nb_pages()
    pdf.add_page()

    # ── Threat Assessment ──
    _threat_badge(pdf, report.get("threat_assessment"))

    # ── Summary ──
    if report.get("summary"):
        pdf.set_font("DejaVu", "", 10)
        pdf.multi_cell(_EW, 5, _safe(report["summary"]))
        pdf.ln(4)

    # ── Per-seed summaries ──
    pss = report.get("per_seed_summaries", {})
    if pss:
        _section_title(pdf, "Per-Seed Summaries")
        for sv, s in pss.items():
            if not isinstance(s, dict):
                continue
            ta = _safe(s.get("threat_assessment", ""))
            r, g, b = _TA_COLORS.get(ta.lower().replace(" ", "_"), (139, 148, 158))
            pdf.set_font("DejaVu", "B", 10)
            pdf.set_text_color(r, g, b)
            pdf.cell(25, 5, f"[{ta.upper()}]")
            pdf.set_text_color(0, 0, 0)
            pdf.set_font("DejaVu", "B", 10)
            pdf.cell(0, 5, f"  {_safe(sv)} ({_safe(s.get('type', ''))})",
                     new_x="LMARGIN", new_y="NEXT")
            if s.get("summary"):
                pdf.set_font("DejaVu", "", 9)
                pdf.multi_cell(_EW, 4.5, _safe(s["summary"]))
            findings = s.get("key_findings", [])
            if findings:
                pdf.set_font("DejaVu", "", 9)
                for f in findings:
                    text = _safe(f.get("text") if isinstance(f, dict) else f)
                    srcs = f.get("sources", []) if isinstance(f, dict) else []
                    src_str = f"  [{', '.join(_safe(x) for x in srcs)}]" if srcs else ""
                    _bullet_cell(pdf, f"{text}{src_str}", multi=True)
            pdf.ln(3)

    # ── Cross-seed findings ──
    csf = report.get("cross_seed_findings", [])
    if csf:
        _section_title(pdf, "Cross-Seed Links")
        pdf.set_font("DejaVu", "", 9)
        for c_item in csf:
            text = _safe(c_item.get("text") if isinstance(c_item, dict) else c_item)
            seeds = c_item.get("seeds", []) if isinstance(c_item, dict) else []
            srcs = c_item.get("sources", []) if isinstance(c_item, dict) else []
            parts = [text]
            if seeds:
                parts.append(f"  [seeds: {', '.join(_safe(x) for x in seeds)}]")
            if srcs:
                parts.append(f"  ({', '.join(_safe(x) for x in srcs)})")
            _bullet_cell(pdf, " ".join(parts), multi=True)
        pdf.ln(3)

    # ── Key findings ──
    kf = report.get("key_findings", [])
    if kf:
        _section_title(pdf, "Key Findings")
        pdf.set_font("DejaVu", "", 9)
        for f in kf:
            text = _safe(f.get("text") if isinstance(f, dict) else f)
            srcs = f.get("sources", []) if isinstance(f, dict) else []
            src_str = f"  [{', '.join(_safe(x) for x in srcs)}]" if srcs else ""
            _bullet_cell(pdf, f"{text}{src_str}", multi=True)
        pdf.ln(3)

    # ── Discriminating markers ──
    dm = report.get("discriminating_markers", [])
    if dm:
        _section_title(pdf, "Discriminating Markers")
        pdf.set_font("DejaVuMono", "", 9)
        for m in dm:
            _bullet_cell(pdf, _safe(m))
        pdf.set_font("DejaVu", "", 9)
        pdf.ln(3)

    # ── IOC List ──
    iocs = report.get("ioc_list", [])
    if iocs:
        _section_title(pdf, "IOC List")
        pdf.set_font("DejaVuMono", "", 9)
        for ioc in iocs:
            _bullet_cell(pdf, _safe(ioc))
        pdf.set_font("DejaVu", "", 9)
        pdf.ln(3)

    # ── Pivot suggestions ──
    ps = report.get("pivot_suggestions", [])
    if ps:
        _section_title(pdf, "Pivot Suggestions")
        pdf.set_font("DejaVu", "", 9)
        for p in ps:
            _bullet_cell(pdf, _safe(p), multi=True)
        pdf.ln(3)

    # ── Graph statistics ──
    _section_title(pdf, "Graph Statistics")
    pdf.set_font("DejaVu", "", 9)
    non_report_nodes = [n for n in nodes if n.get("type") != "report"]
    type_counts = {}
    for n in non_report_nodes:
        t = n.get("type", "unknown")
        type_counts[t] = type_counts.get(t, 0) + 1
    pdf.cell(0, 5, f"Total nodes: {len(non_report_nodes)}  |  Total edges: {len(edges)}",
             new_x="LMARGIN", new_y="NEXT")
    if type_counts:
        parts = [f"{t}: {c}" for t, c in sorted(type_counts.items(), key=lambda x: -x[1])]
        pdf.cell(0, 5, f"Node types: {', '.join(parts)}", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(3)

    # ── Sources used ──
    su = report.get("sources_used", [])
    if su:
        _section_title(pdf, "Sources Used")
        pdf.set_font("DejaVu", "", 9)
        pdf.cell(0, 5, ", ".join(_safe(s) for s in su), new_x="LMARGIN", new_y="NEXT")
        pdf.ln(3)

    # ── Node inventory table ──
    _section_title(pdf, "Node Inventory")
    pdf.set_font("DejaVu", "B", 8)
    pdf.cell(25, 5, "Type", border=1)
    pdf.cell(75, 5, "Value", border=1)
    pdf.cell(45, 5, "Sources Seen", border=1)
    pdf.cell(20, 5, "Tags", border=1)
    pdf.cell(0, 5, "Confidence", border=1, new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("DejaVu", "", 7)
    for n in sorted(non_report_nodes, key=lambda x: x.get("type", "")):
        md = n.get("metadata", {})
        sources_seen = md.get("sources_seen", [])
        tags = n.get("tags", [])
        conf = n.get("confidence", 0)
        val_str = _safe(n.get("value", ""))
        if len(val_str) > 50:
            val_str = val_str[:47] + "..."
        tags_str = ", ".join(_safe(t) for t in tags[:3])
        src_str = ", ".join(_safe(s) for s in sources_seen[:5])
        pdf.cell(25, 4, _safe(n.get("type", "")), border=1)
        pdf.cell(75, 4, val_str, border=1)
        pdf.cell(45, 4, src_str, border=1)
        pdf.cell(20, 4, tags_str, border=1)
        pdf.cell(0, 4, f"{conf:.0%}", border=1, new_x="LMARGIN", new_y="NEXT")

    # ── Timeline ──
    pdf.add_page()
    _section_title(pdf, "Investigation Timeline")
    pdf.set_font("DejaVu", "", 8)
    sorted_nodes = sorted(non_report_nodes, key=lambda x: x.get("created_at", 0))
    for n in sorted_nodes:
        ts = n.get("created_at", 0)
        ts_str = time.strftime("%H:%M:%S", time.localtime(ts)) if ts else "?"
        md = n.get("metadata", {})
        first_seen = md.get("first_seen") or md.get("first_submission_date") or ""
        val_str = _safe(n.get("value", ""))
        if len(val_str) > 60:
            val_str = val_str[:57] + "..."
        line = f"[{ts_str}] {n.get('type', '?'):>10}  {val_str}"
        if first_seen:
            line += f"  (ext. first seen: {_safe(first_seen)})"
        pdf.cell(0, 4, line, new_x="LMARGIN", new_y="NEXT")

    return bytes(pdf.output())
